// The PDF rehab exercises (branch rehab-new-exercises). Decision
// 2026-09-30: these save and show ONLY counts — reps, holds, target,
// points / streaks. No degrees anywhere in their report: the saved
// report hides the calibration card (which prints the calibrated angles)
// for them. Calibration still runs and still sets the lines — it is
// just not shown. The original exercises are unaffected.

export const COUNT_ONLY_SLUGS = new Set([
  "ankle-pumps",
  "biceps-curl",
  "bridge-on-heels",
  "calf-wall-stretch",
  "cervical-flexion-extension",
  "cervical-rotation",
  "cervical-side-flexion",
  "childs-pose",
  "clamshell",
  "copenhagen-plank",
  "cross-body-stretch",
  "dart-throwers-motion",
  "dead-bug",
  "decline-squat",
  "doorway-pec-stretch",
  "eccentric-biceps-curl",
  "eccentric-heel-drops",
  "elbow-arom",
  "foam-roller-thoracic-extension",
  "hamstring-stretch",
  "heel-prop",
  "heel-raises",
  "heel-slides",
  "hip-flexor-stretch",
  "isometric-calf-hold",
  "it-band-stretch",
  "knee-to-chest",
  "lateral-hops",
  "mcgill-curl-up",
  "mckenzie-press-up",
  "median-nerve-slider",
  "nordic-hamstring-curl",
  "open-book",
  "piriformis-stretch",
  "pronation-supination",
  "prone-iyt",
  "prone-thoracic-extension",
  "prone-ytw",
  "pulley-flexion",
  "quad-stretch",
  "quadruped-rock-back",
  "quadruped-weight-shift",
  "rathleff-heel-raise",
  "romanian-deadlift",
  "rows",
  "sciatic-nerve-slider",
  "seated-soleus-raise",
  "seated-thoracic-extension",
  "self-snag",
  "serratus-wall-slide",
  "side-lying-er",
  "side-plank",
  "single-leg-balance",
  "single-leg-bridge",
  "single-leg-hops",
  "sit-to-stand",
  "spanish-squat",
  "standing-hamstring-curl",
  "star-excursion",
  "straight-leg-raise",
  "supine-abduction-slide",
  "table-slides",
  "thread-the-needle",
  "toe-raises",
  "towel-ir-stretch",
  "triceps-extension",
  "ulnar-nerve-tensioner",
  "upper-trap-levator-stretch",
  "wall-finger-walk",
  "wall-push-up",
  "wand-flexion",
  "wrist-curls",
  "eccentric-wrist-flexion",
  "eccentric-wrist-extension",
  "wrist-flexion-extension",
  "wrist-flexor-extensor-stretch",
]);

/** True for an exercise whose report shows counts only. */
export function isCountOnlyExercise(slug) {
  return typeof slug === "string" && COUNT_ONLY_SLUGS.has(slug);
}
